- alias: "kodi starts playing a movie - living room"
  trigger:
    - platform: state
      entity_id: media_player.chromebox
      to: "playing"
  condition:
    condition: sun
    after: sunset
  action:
    - service: scene.turn_on
      entity_id: scene.movie_playing

- alias: "kodi stops or pauses a movie - living room"
  trigger:
    - platform: state
      entity_id: media_player.chromebox
      from: "playing"
  condition:
    condition: sun
    after: sunset
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal
